apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: bandwidth
spec:
  action: bandwidth
  mode: all
  selector:
    labelSelectors:
      "component": "spacemesh"
  direction: to
  bandwidth:
    rate: "2mbps"
    limit: 4194304
    buffer: 1048576