apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: short-disconnect-every-20m
spec:
  schedule: "*/20 * * * *"
  historyLimit: 2
  type: "NetworkChaos"
  networkChaos:
    action: partition
    duration: "60s"
    mode: fixed-percent
    value: "10"
    selector:
      labelSelectors:
        "app": "smesher"
    direction: to
    target:
      mode: all
      selector:
        labelSelectors:
          "component": "spacemesh"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: long-disconnect-every-2h
spec:
  schedule: "0 */2 * * *"
  historyLimit: 2
  type: "NetworkChaos"
  concurrencyPolicy: "Allow"
  networkChaos:
    action: partition
    duration: "2h"
    mode: fixed-percent
    value: "10"
    selector:
      labelSelectors:
        "app": "smesher"
    direction: to
    target:
      mode: all
      selector:
        labelSelectors:
          "component": "spacemesh"