apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: short-failure-every-20m
spec:
  schedule: "*/20 * * * *"
  historyLimit: 2
  type: "PodChaos"
  podChaos:
    action: pod-failure
    mode: fixed-percent
    value: "10"
    selector:
      labelSelectors:
        "app": "smesher"
    duration: "60s"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: long-failure-every-2h
spec:
  schedule: "0 */2 * * *"
  historyLimit: 2
  concurrencyPolicy: "Allow"
  type: "PodChaos"
  podChaos:
    action: pod-failure
    mode: fixed
    value: "2"
    selector:
      labelSelectors:
        "app": "smesher"
    duration: "2h"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: long-failure-every-4h
spec:
  schedule: "0 */4 * * *"
  historyLimit: 2
  concurrencyPolicy: "Allow"
  type: "PodChaos"
  podChaos:
    action: pod-failure
    mode: fixed
    value: "2"
    selector:
      labelSelectors:
        "app": "smesher"
    duration: "4h"
