apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: positive-offset
spec:
  mode: fixed
  value: "5"
  selector:
    labelSelectors:
      "boot": "true"
      "smesher": "true"
  timeOffset: '400ms'
---
apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: negative-offset
spec:
  mode: fixed
  value: "5"
  selector:
    labelSelectors:
      "boot": "true"
      "smesher": "true"
  timeOffset: '-400ms'