apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: positive-timeskew
spec:
  schedule: "*/10 * * * *"
  historyLimit: 2
  type: "TimeChaos"
  concurrencyPolicy: "Allow"
  timeChaos:
    timeOffset: "400ms"
    mode: fixed-percent
    value: "10"
    selector:
      labelSelectors:
        "component": "spacemesh"
    duration: "10m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: negative-timeskew
spec:
  schedule: "*/10 * * * *"
  historyLimit: 2
  type: "TimeChaos"
  concurrencyPolicy: "Allow"
  timeChaos:
    timeOffset: "-400ms"
    mode: fixed-percent
    value: "10"
    selector:
      labelSelectors:
        "component": "spacemesh"
    duration: "10m"