apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: positive-offset
spec:
  mode: all
  selector:
    labelSelectors:
      "bucket-4": "true"
  timeOffset: '400ms'
---
apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: negative-offset
spec:
  mode: all
  selector:
    labelSelectors:
      "bucket-5": "true"
  timeOffset: '-400ms'